### ISSUE TITLE
Destroy popper-conent when parent get's destroyed

### ISSUE THREAD

**Issue by ForstKat** [MrFrankel/ngx-popper#80]
Hey,
I implemented your ngx-popper and created a wrapper component around it for the standard handling of the popper. For performance reasons, I implemented a popperDelay of 250. The problem is that the popper gets also used for add or delete icons. Clicking on it, the parent component gets destroyed but because of the delay the popper trys to render after the 250 ms even when the parent is not there anymore and I get the following error:

`ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'nodeName' of undefined
TypeError: Cannot read property 'nodeName' of undefined`

**Comment by MrFrankel** [comment]
@ForstKat The error should have no effect on the usage.
But ill make sure to fix it ASAP.
Thanks from brining this up.

**Comment by ForstKat** [comment]
Hey @MrFrankel, yeah it is still working but would be good to have no errors there. Did you already investigate it?

**Comment by MrFrankel** [comment]
@ForstKat Should be fixed in 5.1.7, please verify.

**Comment by ForstKat** [comment]
working like a charm. Just did a small test but no more console errors. Thank you sooo much

**Comment by jandresampaio** [comment]
Hi,

Seems this is still an issue in isFixed when parentNode is null. 
Happens when:
1) Component has popper with                                    
`[popperAppendTo]="'body'"`
2) After the component is destroyed (after leaving a route where the component is destroyed)
3) Reenter the component and scroll - isFixed returns the exception reported in this bug description (nodeName of undefined)

Thank you
